#!/bin/bash
# What this script will do:

# 1) Zip's NPANXX.csv
# 2) Updates the publish date in footer of HTM files;

# What this script requires:

# 1) CygWin installed with Zip package included;

# ------------------------------------------------------------------------------------

#	****************************************************************************************
#	*           VERSION CONTROL INFORMATION
#	****************************************************************************************
#	* CVS File:      $RCSfile$
#	* Commit Date:   $Date$ (UTC)
#	* Committed by:  $Author$
#	* CVS Revision:  $Revision$
#	* Checkout Tag:  $Name$ (Version/Build)
#	****************************************************************************************

# ------------------------------------------------------------------------------------

#####################
# DECLARE VARIABLES
#####################

# Directory Variables

BASEDIR="/cygdrive/d/cna/MBIData/"
DOSBASEDIR="d:\\CNA\\MBIData\\"

# Variables

PUBLISHSTAMP="This data was generated by the CNA Master Database on `date "+%F"`."


#####################
# START MAIN SCRIPT
#####################

# Zip NPANXX.csv File

zip ${BASEDIR}MBI.zip ${BASEDIR}MBI.csv

# Remove MBI.csv file
rm ${BASEDIR}MBI.csv

# Update the publish date in HTM Files and remove the NAs

for FILE in ${BASEDIR}*.htm
do
	sed "s/^....insertdatehere.../${PUBLISHSTAMP}/g" ${FILE} | sed "s/N\/A//g" | sed "s/n\/a//g" > ${FILE}_temp
	mv ${FILE}_temp ${FILE}
done

# FOLLOWING LINES USED TO MAIL ADMINS FOR CONFIRMATION OF JOB

#echo "  MBI Data export and prep job has fired" >> ${BASEDIR}blatbody.txt
#echo >> ${BASEDIR}blatbody.txt
#echo >> ${BASEDIR}blatbody.txt

#blat "${DOSBASEDIR}blatbody.txt" -subject "MBI Data Export and Prep fired" -to browng,walshkel -server 192.168.10.151 -from database@saiccanada.com

#rm ${BASEDIR}blatbody.txt


#####################
# END SCRIPT
#####################
